#! /bin/sh

function wait_for_program {
    RESULTS=0
    n=0
    while true
    do
    RESULTS=`xdotool search --onlyvisible --class ${1} | wc -l`
    if [ $RESULTS -ge $2 ]; then
        return 1 
    else
        if [ $n -eq 100 ]; then
            xmessage "Error executing ${1} instance ${2}"
            return 0 
        else
            n=`expr $n + 1`
            sleep .1
        fi
    fi
    done

}

########################
#   workspace 1: urxvt #
########################
i3-msg "workspace urxvt"

urxvt &
wait_for_program "URxvt" 1

i3-msg "split h"

urxvt &
wait_for_program "URxvt" 2
#sleep 1
i3-msg "split v;"

urxvt &
wait_for_program "URxvt" 3
#FOUND=`wait_for_program "URxvt" 3`
#if $FOUND; then
#    exit 0
#else
#    exit 1
#fi

########################
#   workspace 2: devel #
########################

#i3-msg "workspace 2: devel"

#urxvt -e bash -c "/usr/bin/irssi" &
#wait_for_program "URxvt" 1

#i3-msg "split h"

#urxvt &
#wait_for_program "URxvt" 2

#i3-msg "split v"

#urxvt &
#wait_for_program "URxvt" 3

#i3-msg "layout tabbed"
#i3-msg "focus left"
#i3-msg "focus left"
#i3-msg "split v"

#urxvt &
#wait_for_program "URxvt" 4

#i3-msg "layout tabbed"

i3-msg "workspace dev"

urxvt &
wait_for_program "URxvt" 1

i3-msg "split h"

urxvt &
wait_for_program "URxvt" 2

########################
#   workspace ssh      #
########################
i3-msg "workspace ssh"

urxvt -e bash -c "/usr/bin/ssh boveb@shell.onid.oregonstate.edu -t tmux a" &
wait_for_program "URxvt" 1

########################
#   workspace 4: www   #
########################
i3-msg "workspace www"

firefox &
wait_for_program "Firefox" 1

########################
#   workspace 5: file  #
########################
i3-msg "workspace file"

thunar &
wait_for_program "Thunar" 1

########################
#   workspace 7: www   #
########################
i3-msg "workspace www:2"

firefox &
wait_for_program "Firefox" 1

########################
#   workspace 8: devel #
########################
i3-msg "workspace dev:2"

urxvt &
wait_for_program "URxvt" 1

i3-msg "split h"

urxvt &
wait_for_program "URxvt" 2


########################
#   workspace mail     #
########################
i3-msg "workspace mail"

thunderbird &
wait_for_program "Thunderbird" 1

#######################

i3-msg "workspace urxvt"
i3-msg "workspace www:2"
