#! /bin/sh

function wait_for_program {
    RESULTS=0
    n=0
    while true
    do
    RESULTS=`xdotool search --onlyvisible --class ${1} | wc -l`
    if [ $RESULTS -ge $2 ]; then
        return 1
    else
        if [ $n -eq 20 ]; then
            xmessage "Error executing ${1} instance ${2}"
            return 0
        else
            n=`expr $n + 1`
            sleep 1
        fi
    fi
    done

}

i3-msg "workspace 7: www"

firefox &

FOUND=`wait_for_program "URxvt" 1`
if $FOUND; then
    exit 0
else
    exit 1
fi

