#!/bin/sh

device=7

if [ $1 == "mem" ]; then
    #device=4
    device=8
fi

if [ $1 == "cpu" ]; then
    #device=3
    device=7
fi

set -o monitor
top_out=`top -n 1 b | tail -n +8 | sort -n -k ${device} -r | head -1`
pname=$(echo $top_out | awk '{print $11}')
percent=$(echo $top_out | awk "{print \$${device}}")
percent=$(echo "$percent")

percent_len=$(echo $percent | awk '{print length}')
if [ $percent_len -lt 5 ]; then
    padding=$((5-percent_len))
    percent="%${padding}s$percent"
fi

pname_len=$(echo $pname | awk '{print length}')

if [ $pname_len  -lt 15 ]; then
    padding=$((15-pname_len))
    pname="$pname%${padding}s"
fi

if [ $pname_len -gt 15 ]; then
    pname=$(echo $pname | cut -c 1-15)
fi

printf ${pname}${percent}%%
