#!/bin/sh
# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1, "click_events": true }'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

# Now send blocks with information forever:
while true
do
    exec conky -c $HOME/.i3/conkyrc2 &
    read -t 1 line
    exec echo ${line} | $HOME/.i3/scripts/clicky.py &
done

